project:
  type: website
  output-dir: docs

publish:
  method: gh-pages

website:
  title: "Soham Mukherjee"
  search: 
    location: navbar
    type: textbox
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "Publications"
        href: publications/index.qmd
      - text: "Events"
        href: events/index.qmd
      - text: "Teaching"
        href: teaching/index.qmd
      - text: "CV"
        href: cv/index.qmd
        
  page-footer: 
    left: ":copyright: 2025, Soham Mukherjee" 
    #right: 
    #  - text: Impressum
    #    href: impressum/index.qmd
format:
  html:
    theme: 
      light: flatly
      dark: darkly
    #font-family: "Helvetica"
    toggle: true
    page-layout: full
    css: styles.css
    toc: true

#editor: visual

