---
title: "Scientific publications"
format: html
excerpt: "A list of my scientific works"
toc-location: right
page-layout: full
---

## Accepted

### 2026
- *Mukherjee S.*, Claassen M., \& Bürkner P. C. (2026) [Hilbert space methods for approximating multi-output latent variable Gaussian processes](https://doi.org/10.1007/s11222-026-10869-x). Stat Comput 36, 110. [Preprint available for free](https://doi.org/10.48550/arXiv.2505.16919).

### 2025

- *Mukherjee S.*, Claassen M. \& Bürkner PC. (2025) [DGP-LVM: Derivative Gaussian process latent variable models](https://doi.org/10.1007/s11222-025-10644-4). Stat Comput 35, 120. [Preprint available for free](https://arxiv.org/abs/2404.04074).

## In Review

- *Mukherjee S.*, Aguilar J. E., Zago M., Claassen M., \& Bürkner P. C. (2025) [Latent variable estimation with composite Hilbert space Gaussian processes](https://doi.org/10.48550/arXiv.2510.25371). arXiv preprint arXiv:2510.25371.

- Bischoff S., Poličar P. G., *Mukherjee S.*, Macke J. H., Claassen M., \& Schröder C. (2025). [velotest: Statistical assessment of RNA velocity embeddings reveals quality differences for reliable trajectory visualizations](https://www.biorxiv.org/content/10.1101/2025.10.26.683064v1.abstract). bioRxiv, 2025-10.

- Zago M., *Mukherjee S.*, Schleicher J. T., Bürkner P. C., Tabatabai G., Claassen M. (2026) [G-LATO: Inference of Spatial Latent Ordering via Deep Gaussian Processes](https://doi.org/10.64898/2026.06.23.734031). bioRxiv, 2026-06.

## Preprint

- Mukherjee S. (2021) [Bayesian Analysis of Stochastic Volatility Model using Finite Gaussian Mixtures with Unknown Number of Components](https://arxiv.org/abs/2110.12824). arXiv preprint arXiv:2110.12824.

## PhD Thesis

- Mukherjee S. (2025) [On Latent Variable Estimation Using Derivative Gaussian Processes](https://publikationen.uni-tuebingen.de/xmlui/handle/10900/178659), Faculty of Science, University of Tübingen.